keys:
  - &users:
    - &xyven
  - &hosts:
    - &laptop

creation_rules:
  - path_regex: hosts/laptop/secrets.ya?ml$
    key_groups:
    - age:
      - *laptop
      pgp:
      - *xyven
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *laptop
      pgp:
      - *xyven

