keys:
  - &users
    - &xyven age1gteg9ehk9spfkufmg2hfsrzfnk7ejxe20jdgnxvzua7c2ktcd5ys0fgygp
  - &hosts
    - &festus age1hh7j26fwfl8mchs2x7htwd6zeheetxdvvfjtwnhr23v5txjeuvqq7cal6a
creation_rules:
  - path_regex: hosts/festus/secrets.ya?ml$
    key_groups:
    - age:
      - *festus
      - *xyven
