
#
# Misc
#

SW2_PALADIN_REPORT_HANDLER_CLOUD = 0

SW2_PALADIN_WLAN_CONNECTION_TIMEOUT = 30


#
# How to respond to failures
#

SW2_PALADIN_ACTION_FAILACTION_TYPE_FAIL = 0
SW2_PALADIN_ACTION_FAILACTION_TYPE_PROMPT = 1
SW2_PALADIN_ACTION_FAILACTION_TYPE_CONTINUE = 2

#
# Paladin Error Codes
#

SW2_PALADIN_ERROR_NO_ERROR = 0

# Generic errors
SW2_PALADIN_ERROR_INTERNAL = 1
SW2_PALADIN_ERROR_CONFIGURATION_FAILED = 2
SW2_PALADIN_ERROR_ELEVATION_REQUIRED = 3
SW2_PALADIN_ERROR_USER_CANCELLED = 4

# 'action' failed
SW2_PALADIN_ERROR_CERTIFICATE_FAILED = 5
SW2_PALADIN_ERROR_TIMESYNC_FAILED = 6

# Syscheck
SW2_PALADIN_ERROR_SYSCHECK_FAILED = 7
SW2_PALADIN_ERROR_NAC_FAILED = 8
SW2_PALADIN_ERROR_SYSCHECK_DRIVER_WARNING = 9
SW2_PALADIN_ERROR_SYSCHECK_PRODUCT_WARNING = 10
SW2_PALADIN_ERROR_SYSCHECK_SERVICE_WARNING = 11
SW2_PALADIN_ERROR_SYSCHECK_PROCESS_WARNING = 12
SW2_PALADIN_ERROR_SYSCHECK_REGISTRY_WARNING = 13
SW2_PALADIN_ERROR_SYSCHECK_WIRELESS_WARNING = 14

# Enrollment related stuff
SW2_PALADIN_ERROR_ENROLLMENT_FAILED = 15
SW2_PALADIN_ERROR_PREAUTH_FAILED = 16
SW2_PALADIN_ERROR_MISSING_ENROLLMENT_API = 17

# WebSSO stuff
SW2_PALADIN_TLS_ENROLL_WEBSSO_CONFIRM_TYPE_POLLCONNECTOR = 0
SW2_PALADIN_TLS_ENROLL_WEBSSO_CONFIRM_TYPE_SCAN_TBAR = 1
SW2_PALADIN_TLS_ENROLL_WEBSSO_CONFIRM_TYPE_LOCAL_SERVER = 2

# Connection errors
SW2_PALADIN_ERROR_CONNECTION_FAILED = 18
SW2_PALADIN_ERROR_CONNECTION_TIMED_OUT = 19
SW2_PALADIN_ERROR_CONNECTION_FAILED_OTHER = 20
SW2_PALADIN_ERROR_CONNECTION_FAILED_IP = 21
SW2_PALADIN_ERROR_EAP_AUTHENTICATION_FAILED = 22

# Troubleshooting
SW2_PALADIN_ERROR_RESTART_SERVICES_FAILED = 23
SW2_PALADIN_ERROR_RENEW_IP_FAILED = 24
SW2_PALADIN_ERROR_FLUSH_CREDENTIALS_FAILED = 25
